services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /opt/nextcloud_stack/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      - db
      - redis

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    ports:
      - "127.0.0.1:18000:8000"  # Основной порт приложения
      - "127.0.0.1:8443:443"    # SSL порт
    environment:
      - DOC_SERV_ROOT_URL=https://docs.flexites.org
      - JWT_ENABLED=true
      - JWT_SECRET=a8f5f167f44f4964e6c998dee827110c
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice

  web:
    image: nginx:alpine-slim
    restart: always
    ports:
      - 127.0.0.1:8009:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nextcloud_stack/nextcloud:/var/www/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /opt/nextcloud_stack/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  onlyoffice_data:
  onlyoffice_log: